In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
data = pd.read_csv('train.csv')

In [24]:
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [25]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [26]:
Y_train

array([7, 3, 4, ..., 8, 5, 7])

In [27]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

In [28]:
def ReLU(Z):
    return np.maximum(0, Z)

In [29]:
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

In [30]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

In [32]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [31]:
def ReLU_deriv(Z):
    return Z > 0

In [33]:
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

In [34]:
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [35]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [36]:
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [37]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)


Iteration:  0
[2 2 2 ... 2 2 7] [7 3 4 ... 8 5 7]
0.09460975609756098
Iteration:  10
[0 8 4 ... 2 7 7] [7 3 4 ... 8 5 7]
0.1622439024390244
Iteration:  20
[0 8 4 ... 2 7 7] [7 3 4 ... 8 5 7]
0.24253658536585365
Iteration:  30
[0 8 4 ... 3 7 7] [7 3 4 ... 8 5 7]
0.31639024390243903
Iteration:  40
[0 2 4 ... 3 7 7] [7 3 4 ... 8 5 7]
0.38097560975609757
Iteration:  50
[5 2 4 ... 3 7 7] [7 3 4 ... 8 5 7]
0.42360975609756096
Iteration:  60
[5 2 4 ... 3 7 7] [7 3 4 ... 8 5 7]
0.46658536585365856
Iteration:  70
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.5112682926829268
Iteration:  80
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.5535853658536586
Iteration:  90
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.5885853658536585
Iteration:  100
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.617
Iteration:  110
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.6402439024390244
Iteration:  120
[5 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.6605365853658537
Iteration:  130
[7 2 4 ... 3 5 7] [7 3 4 ... 8 5 7]
0.6763414634146342
Iteration:  140
[7 2 4 .